export const CDN_PATH = 'https://3gimg.qq.com/lightmap/xcx/demoCenter/images';
export const COS_PATH = 'https://mapapi.qq.com/web/miniprogram/demoCenter/images'
export const PLUGIN_KEY = '';
export const MOYUAN_KEY = 'JGUBZ-W2HKR-7VNWY-W4JVJ-YEFS3-NQFA4';
export const BAIQIAN_KEY = '';
export const YULU_KEY = '';
export const DIFUNI_KEY = '';
export const INDOOR_KEY = '';
export const REFERER = 'pinche';
export const WEBSERVICE_APPID = 'wxc1c68623b7bdea7b';
export const CUSTOM_KEY = ''; // 个性化地图key
export const WS_HOST = 'https://apis.map.qq.com'
export const SMART_SOLUTION_KEY = ''; //
export const PASSENGERSUBMESSAGE = 'mYUqRgxDsJkV1Ebdi80T0aDHtY0u2H0a0rGsSIQGcos'
export const CARSUBMESSAGE = 'h_1ihdW6gaxligKs_6FWDx6rcM7ko61Qe-yTggYamJk'
