export const CDN_PATH = 'https://3gimg.qq.com/lightmap/xcx/demoCenter/images';
export const COS_PATH = 'https://mapapi.qq.com/web/miniprogram/demoCenter/images'
export const PLUGIN_KEY = '';
export const MOYUAN_KEY = 'JGUBZ-W2HKR-7VNWY-W4JVJ-YEFS3-NQFA4';
export const BAIQIAN_KEY = '';
export const YULU_KEY = '';
export const DIFUNI_KEY = '';
export const INDOOR_KEY = '';
export const REFERER = 'pinche';
export const WEBSERVICE_APPID = 'wxacd407dd20697d1d';
export const CUSTOM_KEY = ''; // 个性化地图key
export const WS_HOST = 'https://apis.map.qq.com'
export const SMART_SOLUTION_KEY = ''; //
export const PASSENGERSUBMESSAGE = 'vTBYeIGWH0DtZcFaq0SgisgU6y_LWAEMS5XZpix2OYA' // chezhu
export const CARSUBMESSAGE = 'nLY1ZuV01mAGSp9stU3gmYSpejgQ_DtQHoqPW8yltcg'
